name: main workflow
on:
  push:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: false

jobs:
  build:
    name: Do before
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  send_telegram:
    name: send status to telegram
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - run: |
          URL="https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
          MESSAGE="
            Status: ${{ contains(needs.*.result, 'failure') && '❌' || '✅' }}
            Project: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            Project: [${{ github.repository }}](https://github.com/${{ github.repository }})
            Env: ${{ github.ref_name == 'PROD' && 'production' || github.ref_name == 'stage' && 'STAGE' }}
          
            Commit message: ${{ github.event.commits[0].message }}
            Additional message: ${{ inputs.message }} 
          
            Run by: ${{ github.actor }}
            Dispatch: ${{ github.event_name == 'workflow_dispatch' && 'manually' || 'auto' }}
            Workflow: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">link</a>
          "
          curl -s -X POST "$URL"\
            --data "chat_id=${{ secrets.TELEGRAM_TO }}"\
            --data "text=$MESSAGE"\
            --data "disable_web_page_preview=1"\
            --data "parse_mode='HTML'"
#          curl\
#            --data "chat_id=${{ secrets.TELEGRAM_TO }}"\
#            --data "disable_web_page_preview=1"\
#            --data "parse_mode=mark"\
#            --data "text=$MESSAGE"\
#            "$URL"
#    steps:
#      - name: send telegram message on push
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          format: html
#          disable_web_page_preview: true
#          message: |
#            Status: ${{ contains(needs.*.result, 'failure') && '❌' || '✅' }}
#            Project: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
#            Env: ${{ github.ref_name == 'PROD' && 'production' || github.ref_name == 'stage' && 'STAGE' }}
#
#            Commit message: ${{ github.event.commits[0].message }}
#            Additional message: ${{ inputs.message }}
#
#            Run by: ${{ github.actor }}
#            Dispatch: ${{ github.event_name == 'workflow_dispatch' && 'manually' || 'auto' }}
#            Workflow: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">link</a>
