name: main workflow
on:
  push:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: false

jobs:

  build:
    name: Do before
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  fail:
    name: fail step
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1

  send_telegram:
    name: send status to telegram
    needs: [build, fail]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            Status: ${{ contains(needs.*.result, 'failure') && '❌' || '✅' }}
            Project: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            Env: ${{ github.ref_name == 'PROD' && 'production' || github.ref_name == 'stage' && 'STAGE' }}
            Dispatch: ${{ github.event_name == 'workflow_dispatch' && 'manually' || 'auto' }}
            
            Commit message: ${{ github.event.commits[0].message }}
            Additional message: ${{ inputs.message }} 
            
            Run by: ${{ github.actor }}
            Workflow: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">link</a>
